---
- name: Install Docker
  yum:
    name: docker
    state: latest
  become: yes

- name: add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
  become: yes

- name: Copy service init file
  copy:
    src: ../files/docker
    dest: /etc/init.d/docker
    owner: root
    group: root
    mode: 0755
  become: yes

- name: enable docker service
  command: systemctl enable docker
  register: myoutput

- name: start docker service
  service:
    name: docker
    state: started