---
- name: Check if java1.8 package exists
  yum:
    list=docker
  register: docker

- name: Install Docker
  yum:
    name: docker
    state: latest
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0


- name: add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: Copy service init file
  copy:
    src: ../files/docker
    dest: /etc/init.d/docker
    owner: root
    group: root
    mode: 0755
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: enable docker service
  command: systemctl enable docker
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: start docker service
  service:
    name: docker
    state: started
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: add the docker registry crt for the daemon
  copy:
    src: ../files/18.130.226.162.crt
    dest: /etc/docker/certs.d/ec2-18-130-226-162.eu-west-2.compute.amazonaws.com/ca.crt
    owner: ec2-user
    group: ec2-user
  become: yes
