---
- name: create the .m2 dir
  file:
    path: /home/ec2-user/.m2/
    state: directory
    owner: ec2-user
    group: ec2-user
  become: yes

- name: Copy service init file
  copy:
    src: ../files/settings.xml
    dest: /home/ec2-user/.m2/settings.xml
    owner: root
    group: root
    mode: 0755
  become: yes
  when: docker.results | selectattr("yumstate", "match", "installed") | list | length == 0
