#!groovy
import java.rmi.server.ExportException

pipeline {
    agent {label 'rpm'}

    stages {
        stage('Build') {
            steps {
                echo '------------ Building ------------'
                try {
                    withEnv(["JAVA_HOME=${ tool 'jdk1.8' }", "PATH+MAVEN=${tool 'm2'}/bin:${env.JAVA_HOME}/bin"]) {
                        sh "mvn --batch-mode -V -U -e clean compile"
                    }
                } catch (Exception e) {
                    error("Build Failed: " + e.printStackTrace())
                }
            }
        }
        stage('Test') {
            steps {
                echo '------------ Testing ------------'
                try {
                    withEnv(["JAVA_HOME=${ tool 'jdk1.8' }", "PATH+MAVEN=${tool 'm2'}/bin:${env.JAVA_HOME}/bin"]) {
                        sh "mvn --batch-mode -V -U -e clean test"
                    }
                } catch (Exception e) {
                    error("Build Failed: " + e.printStackTrace())
                }
            }
        }
        stage('Build WAR') {
            steps {
                echo '------------ Building the WAR ------------'
                try {
                    withEnv(["JAVA_HOME=${ tool 'jdk1.8' }", "PATH+MAVEN=${tool 'm2'}/bin:${env.JAVA_HOME}/bin"]) {
                        sh "mvn --batch-mode -V -U -e clean package -DskipTests"
                    }
                    archiveArtifacts artifacts: 'sm-shop/target/*.war', onlyIfSuccessful: true
                } catch (Exception e) {
                    error("Build failed because: " + e.printStackTrace())
                }
            }

        }
    }
}