---
- name: Copy diwnload script
  copy:
    src: ../files/download_JDK.sh
    dest: /tmp/jdk/
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Run the download script
  shell: ./download_JDK.sh
  args:
    chdir: /tmp/jdk/
  become: yes

- name: install JDK rpm from a local file
  shell: yum install -y $(ls jdk*.rpm)
  args:
    chdir: /tmp/jdk/
  become: yes