---
- name: Chceck if settings.xml exists
  stat: path=/home/ec2-user/.m2/settings.xml
  register: settingsFile


- name: create the .m2 dir
  file:
    path: /home/ec2-user/.m2/
    state: directory
    owner: ec2-user
    group: ec2-user
  become: yes
  when: settingsFile.stat.exists == false

- name: Copy service init file
  copy:
    src: ../files/settings.xml
    dest: /home/ec2-user/.m2/settings.xml
    owner: ec2-user
    group: ec2-user
    mode: 0755
  become: yes
  when: settingsFile.stat.exists == false