[slaves]
35.178.213.105          ansible_ssh_private_key_file=/var/jenkins_home/aws-london.pem
35.176.104.237          ansible_ssh_private_key_file=/var/jenkins_home/aws-london.pem
35.178.147.137          ansible_ssh_private_key_file=/var/jenkins_home/aws-london.pem